[build-system]
requires = ["maturin>=1.13,<2.0"]
build-backend = "maturin"

[project]
name = "native-dialog"
description = "native-dialog-rs python port and command-line interface"
requires-python = ">=3.10"
readme="README.md"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: macOS",
    "Operating System :: POSIX :: Linux",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = ["version"]
keywords = ["dialog", "window", "rust", "open", "file"]
dependencies = [
    "pytest>=9.0.3",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "UP", "W", "I", "F"]
ignore = ["E501", "E402", "S101", "F403"]
